### ISSUE TITLE
doesnt open at all

### ISSUE THREAD

**Issue by randomstuff69** [BigheadSMZ/PGS#1]
when i double click it nothing opens

**Comment by samuwersonst** [comment]
The .exe file seems to be missing, I don't know how to start the program without...

**Comment by BigheadSMZ** [comment]
@randomstuff69 :  Can you give a bit more info such as what version of Windows are you using? I haven't tested on anything before Windows 11, but it should work on any OS that supports .NET Framework 4.8 which goes back to Windows 7 SP1.

@samuwersonst : The exe file should be in the archive. It's possible some antivirus is false flagging it and removing it before you even get the chance to see it's there.
![image](https://github.com/user-attachments/assets/d62c6bff-1a59-4e65-81b6-ab738009676d)

**Comment by jmsether** [comment]
I am having this issue as well with 1.4.1 and 1.4.2. I am on windows 11 and it is not functioning correct. I have checked that I have 4.8 net and it still does not open.

**Comment by jmsether** [comment]
Did some playing with the code and I managed to fix the problem. It seems windows can also report virtual monitors which have no height or width and don't show up on the ScrHeight array throwing an out of bounds error. I have added a check for this and might submit a pull request later.

**Comment by jmsether** [comment]
Someone want to double check this works on their machine before I do a pull request. preferably @BigheadSMZ 
https://github.com/jmsether/PGS

**Comment by jmsether** [comment]
No worries, I'll send that PR now.

**Comment by BigheadSMZ** [comment]
Will someone please test the latest release to see if it fixes the issue?
https://github.com/BigheadSMZ/PGS/releases/download/v1.4.3/PGS.v1.4.3.zip

**Comment by BigheadSMZ** [comment]
Since it's been a week and nobody with the issue has responded, I am going to assume that the issue is fixed. If this issue or any other issue remains, go ahead and create a new report.
